# Generated by Django 4.2.3 on 2023-07-17 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=3)),
                ('Address', models.TextField()),
                ('ContactNumber', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=3)),
                ('Specialty', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('gynecology', 'Gynecology'), ('oncology', 'Oncology'), ('dermatology', 'Dermatology')], max_length=100)),
                ('ContactNumber', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppointmentDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('DoctorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.doctor')),
                ('PatientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.patient')),
            ],
        ),
    ]
